namespace BaselessJumping.Enums
{
    public enum TileFraming : sbyte
    {
        TopLeft,
        Top,
        TopRight,
        Left,
        Middle,
        Right,
        BottomLeft,
        Bottom,
        BottomRight,
        LeftRight,
        Up,
        FacingLeft,
        UpDown,
        FacingRight,
        Down,
        Neutral,
        TopLeftCorner,
        TopRightCorner,
        BottomLeftCorner,
        BottomRightCorner,
        RightUpDown,
        LeftUpDown,
        UpLeftRight,
        DownLeftRight
    }
}